# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  codespell:
    docker:
    - image: circleci/python

    steps:
    - checkout
    - run: sudo pip install codespell
    - run: codespell --skip=".git,./vendor"

  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/mjtrangoni/pacemaker_exporter

    environment:
     - DOCKER_IMAGE_NAME: "mjtrangoni/pacemaker_exporter"
     - QUAY_IMAGE_NAME: "quay.io/mjtrangoni/pacemaker_exporter"
    steps:
      # checkout the project
      - checkout
      # Docker
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.03.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            ls -la /tmp/docker
            sudo mv /tmp/docker/* /usr/bin/
            docker info
      # make and test
      - run:
          name: Binary Build
          command: make
      # quay build
      - run:
          name: Quay.io Build
          command: docker build -t $QUAY_IMAGE_NAME:$CIRCLE_BRANCH .
      - run:
          name: Quay Login
          command: docker login -u $QUAYLOGIN -p $QUAYPASSWORD quay.io
      - run:
          name: Quay Push
          command: docker push $QUAY_IMAGE_NAME:$CIRCLE_BRANCH
      - run:
          name: Docker Build
          command: make docker
      - run:
          name: Docker Login
          command: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run:
          name: Docker Push
          command : docker push $DOCKER_IMAGE_NAME:$CIRCLE_BRANCH

workflows:
  version: 2
  flexlm_exporter:
    jobs:
    - codespell:
        filters:
          tags:
            only: /.*/
    - build:
        # This enable the environment variables
        context: org-global
        filters:
          tags:
            only: /.*/
